name: Discord Action

on:
  push:
    branches: [ main ]

jobs:
  react_on_push:
    runs-on: ubuntu-latest
    steps:
    - name: Send Discord notification
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: success
        title: "📢 New push to Frontend repo"
        color: 5965F2
        description: |
          **Repository:** [${{ github.repository }}](https://github.com/${{ github.repository }})
          **Author:** ${{ github.event.head_commit.author.name }}
          **Message:** ${{ github.event.head_commit.message }}
          **Commit:** [View Commit](${{ github.event.head_commit.url }})

